# Generated by Django 4.1.6 on 2023-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
