# Generated by Django 4.1.6 on 2023-02-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETE', 'COMPLETE'), ('COMFIRM', 'COMFIRM')], default='OPEN', max_length=20),
        ),
    ]
